Added ability for solver to account for leakage in the vessel, as well as relevant test cases for validation.
SimVascular/svOneDSolver pull request #109
Opened 2023-11-17 01:39 UTC by JRao-rgb

## Current situation
*Link any open issues or PRs related to this PR. Please ensure that all non-trivial PRs are first tracked and discussed in an existing GitHub issue or discussion.*

## Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*

## Documentation
 
*Please ensure that you properly document any additions.*

## Testing
*Please ensure that the PR meets the testing requirements set by GitHub Actions.*
 
*In addition, please ensure all modified and new code is covered by tests.*

## Code of Conduct & Contributing Guidelines 
- [ ] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2023-11-17 02:31 UTC, JRao-rgb commented
@mrp089  should be good to merge! Please take a look when you have time and let me know if I've missed anything!

2023-11-17 23:20 UTC, mrp089 requested changes
Looks good, @JRao-rgb! Just some minor comments.

Please also update the [ROM Simulation guide](https://github.com/SimVascular/simvascular.github.io/tree/main/documentation/rom_simulation/1d-solver) so others can see your new feature at the following places:
- [input file](https://github.com/SimVascular/simvascular.github.io/blob/main/documentation/rom_simulation/1d-solver/input_file/readme.md) (mention outflow option)
- [theory](https://github.com/SimVascular/simvascular.github.io/blob/main/documentation/rom_simulation/1d-solver/theory/readme.md) (mention $\psi$ in the text)

Just follow the same process you did for this PR: fork the repository, create a branch, make the edits, open a PR (reference this PR - no need to create a new issue). The `HTML` will be generated automatically from the `.md` markdown files once the PR is merged.

Congratulations on adding the first new `1D` feature in a long time!

2023-11-17 23:20 UTC, mrp089 commented on Code/Source/cvOneDMaterial.h
Ideally, the files changed/added in #108 should not be changed here. However, it's not worth it to split up this pull request. We'll merge #108 first and then update this branch (which might bring on conflicts that will be easy to resolve)

2023-11-17 23:20 UTC, mrp089 commented on Code/Source/cvOneDMaterialOlufsen.cxx
> +  return L_P*(pressure - P_ambient); // JR 10/11/23: added function for outflow term
No need for date/initials

2023-11-17 23:20 UTC, mrp089 commented on Code/Source/cvOneDMaterialOlufsen.h
> +    double GetFoo() {return K1_;};
Is `GetFoo` used?

2023-11-17 23:20 UTC, mrp089 commented on tests/__pycache__/__init__.cpython-39.pyc
Remove `*.pyc` and add to `.gitignore` with `__pycache__`

2023-11-17 23:20 UTC, mrp089 commented on tests/cases/bifurcation_R.in
Check out from master branch since only formatting changed

2023-11-17 23:20 UTC, mrp089 commented on Code/Source/cvOneDBFSolver.cxx
Check out from master branch

2026-03-13 02:10 UTC, ktbolt commented
No recent activity here.

2026-03-13 02:10 UTC, closed without merging